server:
  port: 8080

spring:
  application:
    name: online-event-management-system-api
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null
  profiles:
    active: local
  r2dbc:
    url: ${DB_URL}
    name: ${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    pool:
      enabled: true
      initial-size: 5
      max-size: 15
      max-acquire-time: 20s
      max-life-time: 5m
      max-idle-time: 10m
      max-create-connection-time: 60s

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"
